"""initial schema with tenancy

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 11:55:44.563539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('limit_overrides', sa.JSON(), nullable=False),
    sa.Column('billing_customer_id', sa.String(length=255), nullable=True),
    sa.Column('billing_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_billing_customer_id'), 'organizations', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lookup_id', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('display_hint', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_lookup_id'), 'api_keys', ['lookup_id'], unique=True)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_org_created', 'audit_log', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'url', name='uq_site_org_url')
    )
    op.create_index(op.f('ix_sites_host'), 'sites', ['host'], unique=False)
    op.create_index(op.f('ix_sites_org_id'), 'sites', ['org_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'period', 'metric', name='uq_usage_org_period_metric')
    )
    op.create_index(op.f('ix_usage_counters_org_id'), 'usage_counters', ['org_id'], unique=False)
    op.create_index('ix_usage_org_period', 'usage_counters', ['org_id', 'period'], unique=False)
    op.create_table('crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('pages_skipped_robots', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawls_org_id'), 'crawls', ['org_id'], unique=False)
    op.create_index(op.f('ix_crawls_site_id'), 'crawls', ['site_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('experiment', sa.String(length=128), nullable=False),
    sa.Column('condition', sa.String(length=128), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('chunker', sa.JSON(), nullable=False),
    sa.Column('retriever', sa.JSON(), nullable=False),
    sa.Column('index_stats', sa.JSON(), nullable=False),
    sa.Column('projection', sa.JSON(), nullable=False),
    sa.Column('aggregate', sa.JSON(), nullable=False),
    sa.Column('n_queries', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_runs_experiment'), 'experiment_runs', ['experiment'], unique=False)
    op.create_index(op.f('ix_experiment_runs_org_id'), 'experiment_runs', ['org_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('weights_fitted', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_org_id'), 'audits', ['org_id'], unique=False)
    op.create_index(op.f('ix_audits_site_id'), 'audits', ['site_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_id', 'url', name='uq_page_crawl_url')
    )
    op.create_index(op.f('ix_pages_crawl_id'), 'pages', ['crawl_id'], unique=False)
    op.create_index(op.f('ix_pages_doc_id'), 'pages', ['doc_id'], unique=False)
    op.create_table('query_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('ranked_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('n_relevant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'query_id', name='uq_query_run')
    )
    op.create_index(op.f('ix_query_records_run_id'), 'query_records', ['run_id'], unique=False)
    op.create_index('ix_query_records_run_query', 'query_records', ['run_id', 'query_id'], unique=False)
    op.create_table('page_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'page_id', name='uq_score_audit_page')
    )
    op.create_index(op.f('ix_page_scores_audit_id'), 'page_scores', ['audit_id'], unique=False)
    op.create_index(op.f('ix_page_scores_page_id'), 'page_scores', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_scores_page_id'), table_name='page_scores')
    op.drop_index(op.f('ix_page_scores_audit_id'), table_name='page_scores')
    op.drop_table('page_scores')
    op.drop_index('ix_query_records_run_query', table_name='query_records')
    op.drop_index(op.f('ix_query_records_run_id'), table_name='query_records')
    op.drop_table('query_records')
    op.drop_index(op.f('ix_pages_doc_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_crawl_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_audits_site_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_org_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_experiment_runs_org_id'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_experiment'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_crawls_site_id'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_org_id'), table_name='crawls')
    op.drop_table('crawls')
    op.drop_index('ix_usage_org_period', table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_org_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_sites_org_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_host'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_org_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_lookup_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_billing_customer_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
